config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('search/', include('haystack.urls')),
    path('', include('shop.urls')),
    path('member/', include('member.urls')),
]



# 23. 프로젝트 최상위에 templates 디렉토리 생성
# 24. .templates 폴더에 base.html 화일 만들고 coding 복사


# 71. .config/urls.py 수정 삭제
# 29. .config/urls.py static을 사용해서 MEDIA_URL에 해당하는 주소를 가진 요청에 대해서는 MEDIA_ROOT에서 찾아서 응답하도록 urlpatterns에 추가하는 구문. 이 구문은 디버그 모드가 True일 때만 동작함.
#from django.conf.urls.static import static
#from django.conf import settings

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 30. pip install django-allauth : 소셜로그인 추가하기
# 31. .config/settings.py INSTALLED_APPS에 App(allauth) 추가

member/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'member'

urlpatterns = [
    path('profile_update/', login_required(ProfileUpdateView.as_view()), name='profile_update'),
    path('profile/<int:pk>/', login_required(ProfileView.as_view()), name='profile'),
    path('profile_delete/', login_required(profile_delete), name='profile_delete'),
    path('password/', login_required(change_password), name='change_pw'),
]

# 39. .member/views.py coding 복사

shop/urls.py
from django.urls import path
from .views import *



app_name = 'shop'


urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('categories/<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('mypage/<int/pk>/', product_mypage, name='product_mypage'),
    path('<int:pk>/<product_slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('upload/', ProductUploadView.as_view(), name='product_upload'),
    path('search/', search, name='search'),
    path('delete/<int:pk>/<product_slug>/', ProductDeleteView.as_view(), name='product_delete'),
    path('update/<int:pk>/<product_slug>/', ProductUpdatedView.as_view(), name='product_update'),
]


# 22. .config/urls.py 에서 url 연결 coding 복사

member/models.py
from django.conf import settings
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, # <- 특정 사용자 모델에 종속적이지 않다.
        on_delete=models.CASCADE
    )
    phone = models.CharField(
        max_length=100
    )

    class Meta:
        db_table = 'account_profile'
        app_label = 'account' # <- account 앱 카테고리에서 관리되도록 한다.


# 41. .member/forms.py 화일 생성 후 coding 복사

member/forms.py
from django import forms
from django.contrib.auth.models import User

from django.utils.translation import ugettext_lazy as _

from .models import Profile


class SignupForm(forms.Form):
    first_name = forms.CharField(label=_('First name'),
                                 max_length=30,
                                 widget=forms.TextInput(
                                     attrs={'placeholder':
                                                _('First name'), }))
    last_name = forms.CharField(label=_('Last name'),
                                max_length=30,
                                widget=forms.TextInput(
                                    attrs={'placeholder':
                                               _('Last name'), }))
    phone = forms.CharField(label=_('Phone number'),
                            max_length=30,
                            widget=forms.TextInput(
                                attrs={'placeholder':
                                           _('Phone number'), }))

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

        profile = Profile()
        profile.user = user
        profile.phone = self.cleaned_data['phone']
        profile.save()

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone']


# 42. .member/admin.py coding 복수

member/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views import View

from .forms import UserForm, ProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password



class ProfileUpdateView(View): # 간단한 View클래스를 상속 받았으므로 get함수와 post함수를 각각 만들어줘야한다.
    # 프로필 편집에서 보여주기위한 get 메소드
    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk)  # 로그인중인 사용자 객체를 얻어옴
        user_form = UserForm(initial={
            'first_name': user.first_name,
            'last_name': user.last_name,
        })

        if hasattr(user, 'profile'):  # user가 profile을 가지고 있으면 True, 없으면 False (회원가입을 한다고 profile을 가지고 있진 않으므로)
            profile = user.profile
            profile_form = ProfileForm(initial={
                'phone': profile.phone,
            })
        else:
            profile_form = ProfileForm()

        return render(request, 'member/profile_update.html', {"user_form": user_form, "profile_form": profile_form})
    # 프로필 편집에서 실제 수정(저장) 버튼을 눌렀을 때 넘겨받은 데이터를 저장하는 post 메소드
    def post(self, request):
        u = User.objects.get(id=request.user.pk)  # 로그인중인 사용자 객체를 얻어옴
        user_form = UserForm(request.POST, instance=u)  # 기존의 것의 업데이트하는 것 이므로 기존의 인스턴스를 넘겨줘야한다. 기존의 것을 가져와 수정하는 것

        # User 폼
        if user_form.is_valid():
            user_form.save()

        if hasattr(u, 'profile'):
            profile = u.profile
            profile_form = ProfileForm(request.POST, request.FILES, instance=profile)  # 기존의 것 가져와 수정하는 것
        else:
            profile_form = ProfileForm(request.POST, request.FILES)  # 새로 만드는 것

        # Profile 폼
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)  # 기존의 것을 가져와 수정하는 경우가 아닌 새로 만든 경우 user를 지정해줘야 하므로
            profile.user = u
            profile.save()

        return redirect('member:profile', pk=request.user.pk) # 수정된 화면 보여주기



class ProfileView(DetailView):
    context_object_name = 'profile_user' # model로 지정해준 User모델에 대한 객체와 로그인한 사용자랑 명칭이 겹쳐버리기 때문에 이를 지정해줌.
    model = User
    template_name = 'member/profile.html'




def profile_delete(request):
    if request.method == 'POST':
        request.user.delete()
        return redirect('/')
    return render(request, 'member/profile_delete.html')


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return render(request, 'member/password_done.html', {'form': form})
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'member/change_pw.html', {
        'form': form
    })


# 40. .member/models.py coding 복사 : phone number를 위한 model

member/templates/member/change_pw.html
{% extends 'base.html' %}
{% block title %}- Change Password{% endblock %}

{% block content %}

<div class="col">
        <div class="alert alert-info text-primary " role="alert">
            <h1>{{user.username}}'s Change the Password</h1>
        </div>
    <form method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="변경">
    </form>

</div>
{% endblock %}

member/templates/member/password_done.html
{% extends 'base.html' %}
{% block title %}- Change Password{% endblock %}

{% block content %}

<div class="col">
        <div class="alert alert-danger mt-5 text-primary " role="alert">
            <h5>{{user.username}}'s password was successfully updated!</h5>
        </div>
    <a href="/"><button type="button" class="btn btn-info mt-1 btn-xs float-right">Continue shopping</button></a>
</div>


{% endblock %}

member/templates/member/profile.html
{% extends 'base.html' %}
{% block title %}- Profile{% endblock %}

{% block content %}
<div class="col">
        <div class="alert alert-info text-primary " role="alert">
            <h2>{{user.username}}'s profile</h2>
        </div>



    <div class="col">
        <h5> USER : {{profile_user.username}} <br>
            {% if profile_user.first_name is not None %}
            NAME : {{profile_user.first_name}} {{profile_user.last_name}} <br>
            PHONE : {{profile_user.phone}}<br>
            EMAIL : {{profile_user.email}}<br>
            {% endif %}
        </h5>
        <p></p>
        {% if user == profile_user %}   <!-- 로그인한 사용자와 profile_user(프로필 소유자)가 일치할 때만 프로필 편집이 가능하도록 함 -->
        <a href="{% url 'member:profile_update' %}">
            <button type="button" class="btn btn-default mt-1 ">프로필 편집</button></a>
        <a href="{% url 'member:change_pw' %}">
            <button type="button" class="btn btn-default mt-1 ">비밀번호 변경</button><a>
        <a href="{% url 'member:profile_delete' %}">
            <button type="button" class="btn btn-default mt-1 ">회원 탈퇴</button></a>
        {% endif %}
        <a href="/"><button type="button" class="btn btn-info mt-1 btn-xs">Continue shopping</button></a>

    </div>
</div>

{% endblock %}

member/templates/member/profile_del_done.html
{% extends 'base.html' %}
{% block title %}- Change Password{% endblock %}

{% block content %}

<div class="col">
        <div class="alert alert-danger mt-5 text-primary " role="alert">
            <h5>{{user.username}} has closed the account!</h5>
        </div>
    <a href="/"><button type="button" class="btn btn-info mt-1 btn-xs float-right">Continue shopping</button></a>
</div>


{% endblock %}

member/templates/member/profile_delete.html
{% extends 'base.html' %}
{% block title %}- Profile Delete{% endblock %}

{% block content %}

<div class="col">
        <div class="alert alert-info text-primary " role="alert">
            <h1>{{user.username}}, User Delete</h1>
        </div>

<form method="POST">
    {% csrf_token %}
    <p>정말로 탈퇴하시겠습니까? | Do you want to close your account?</p>
    <input type="submit" value="회원 탈퇴">
</form>

{% endblock %}

member/templates/member/profile_update.html
{% extends 'base.html' %}
{% block title %}- Member{% endblock %}

{% block content %}
<div class="col">
        <div class="alert alert-info text-primary " role="alert">
            <h1>{{user.username}}'s profile update</h1>
        </div>


    {% if error_msg %}
    <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Error</strong> {{error_msg}}
    </div>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Update" >
    </form>
</div>


{% endblock %}

<!-- python manage.py makemigrations
     python manage.py migrate
     46. .config/settings.py INSTALLED_APPS에 App(haystack) 추가  -->