config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('search/', include('haystack.urls')),
    path('', include('shop.urls')),
    path('member/', include('member.urls')),
]



# 23. 프로젝트 최상위에 templates 디렉토리 생성
# 24. .templates 폴더에 base.html 화일 만들고 coding 복사


# 71. .config/urls.py 수정 삭제
# 29. .config/urls.py static을 사용해서 MEDIA_URL에 해당하는 주소를 가진 요청에 대해서는 MEDIA_ROOT에서 찾아서 응답하도록 urlpatterns에 추가하는 구문. 이 구문은 디버그 모드가 True일 때만 동작함.
#from django.conf.urls.static import static
#from django.conf import settings

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 30. pip install django-allauth : 소셜로그인 추가하기
# 31. .config/settings.py INSTALLED_APPS에 App(allauth) 추가

member/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'member'

urlpatterns = [
    path('profile_update/', login_required(ProfileUpdateView.as_view()), name='profile_update'),
    path('profile/<int:pk>/', login_required(ProfileView.as_view()), name='profile'),
    path('profile_delete/', login_required(profile_delete), name='profile_delete'),
    path('password/', login_required(change_password), name='change_pw'),
]

# 39. .member/views.py coding 복사

shop/urls.py
from django.urls import path
from .views import *



app_name = 'shop'


urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('categories/<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('mypage/<int/pk>/', product_mypage, name='product_mypage'),
    path('<int:pk>/<product_slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('upload/', ProductUploadView.as_view(), name='product_upload'),
    path('search/', search, name='search'),
    path('delete/<int:pk>/<product_slug>/', ProductDeleteView.as_view(), name='product_delete'),
    path('update/<int:pk>/<product_slug>/', ProductUpdatedView.as_view(), name='product_update'),
]


# 22. .config/urls.py 에서 url 연결 coding 복사

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- jquery slim 지우고 minified 추가 -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <style>
     .title h1,
    .title h3,
    .title h5 {
      display: inline;
    }
    </style>


    {% block script %}
    {% endblock %}

    {% block style %}
    {% endblock %}
</head>



<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="title">
        <a class="navbar-brand" href="/"><h1 class="text-primary">Logippl</h1><h3 class="text-muted">DadaSOL</h3><h5>Beta</h5></a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav justify-content-end">
        <li class="nav-item">
            <li class="nav-item"><a href="/" class="active nav-link ">Home</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'shop:product_mypage' %}" class="nav-link">Welcome, {{user.get_username}}</a></li>
            <li class="nav-item"><a href="{% url 'shop:search' %}" class="nav-link">Search</a></li>
            <li class="nav-item"><a href="{% url 'shop:product_upload' %}" class="nav-link">Upload</a></li>
            <li class="nav-item"><a href="{% url 'member:profile' user.pk %}" class="nav-link">MyAccount</a></li>
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'account_login' %}">Login(Sign Up)</a>
            {% endif %}


        </li>


    </ul>
  </div>
</nav>
<div class="container">
{% block content %}
{% endblock %}
</div>


</body>
</html>

<!-- 25. .cofig/settings.py 에 템플릿 검색되도록 경로 추가, TEMPLATES 변수에 있는 DIRS키의 값에 추가 -->