config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('search/', include('haystack.urls')),
    path('', include('shop.urls')),
    path('member/', include('member.urls')),
]



# 23. 프로젝트 최상위에 templates 디렉토리 생성
# 24. .templates 폴더에 base.html 화일 만들고 coding 복사


# 71. .config/urls.py 수정 삭제
# 29. .config/urls.py static을 사용해서 MEDIA_URL에 해당하는 주소를 가진 요청에 대해서는 MEDIA_ROOT에서 찾아서 응답하도록 urlpatterns에 추가하는 구문. 이 구문은 디버그 모드가 True일 때만 동작함.
#from django.conf.urls.static import static
#from django.conf import settings

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 30. pip install django-allauth : 소셜로그인 추가하기
# 31. .config/settings.py INSTALLED_APPS에 App(allauth) 추가

shop/urls.py
from django.urls import path
from .views import *



app_name = 'shop'


urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('categories/<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('mypage/<int/pk>/', product_mypage, name='product_mypage'),
    path('<int:pk>/<product_slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('upload/', ProductUploadView.as_view(), name='product_upload'),
    path('search/', search, name='search'),
    path('delete/<int:pk>/<product_slug>/', ProductDeleteView.as_view(), name='product_delete'),
    path('update/<int:pk>/<product_slug>/', ProductUpdatedView.as_view(), name='product_update'),
]


# 22. .config/urls.py 에서 url 연결 coding 복사

shop/models.py
from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    meta_description = models.TextField(blank=True)

    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_in_category', args=[self.slug])


class Product(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_products')

    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    cname = models.CharField('Company', max_length=200, db_index=True)
    pname = models.CharField('Products', max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True,
                            help_text='모델명, 제조사, 키워드 등을 조합하여 띄어 쓰기(공란) 없이 입력합니다. (공란은 "_"를 이용)')

    image = models.ImageField(upload_to='products/%Y/%m/%d', null=True)
    related_url = models.TextField(blank=True)
    description = models.TextField(blank=True)
    meta_description = models.TextField('Meta', blank=True)

    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    unit_price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.PositiveIntegerField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        index_together = [['id', 'slug']]

    def __str__(self):
        return "[ " + self.cname + " | " + self.pname + " | " + self.created.strftime(
            "%Y-%m-%d %H:%M:%S" + " ]")

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


'''
11. pip install pillow
12. python manage.py makemigrations shop
13. python manage.py migrate shop 0001
14. .config/setting.py 에 MEDIA_ROOT 옵션 설정
'''

shop/views.py
from django.shortcuts import render, get_object_or_404


from .models import *
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import redirect
from django.views.generic.detail import DetailView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator



def product_in_category(request, category_slug=None):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True)


    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)


    return render(request, 'shop/list.html',
                  {'current_category': current_category, 'categories': categories, 'products': products})





@method_decorator(login_required, name="dispatch")
class ProductDetailView(DetailView):

    model = Product
    template_name = 'shop/detail.html'


    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product_list'] = Product.objects.all()
        return context

index = ProductDetailView.as_view()




@login_required
def product_mypage(request):
    products = Product.objects.all()
    return render(request, 'shop/mypage.html', {'products':products})



class ProductUploadView(LoginRequiredMixin, CreateView):
    login_url = 'accounts/login/'
    redirect_field_name = 'redirect_to'
    model = Product
    fields = ['category', 'image', 'cname', 'pname', 'related_url', 'description', 'meta_description', 'slug', 'unit_price', 'stock', 'available_display', 'available_order']
    prepopulated_fields = {'slug': ('cname', 'pname', 'meta_description')}
    template_name = 'shop/upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form':form})



class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Product
    success_url = '/'
    template_name = 'shop/delete.html'

class ProductUpdatedView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Product
    fields = ['image','cname', 'pname', 'related_url', 'description', 'meta_description', 'slug', 'unit_price', 'stock',]
    template_name = 'shop/update.html'









from .search_indexes import *

@login_required
def search(request):
    search_form = NoteIndex()
    return render(request, 'search/search.html', {'form':search_form})


'''
20. .shop 폴더에 urls.py 생성
21. .shop/urls.py 에서 url 연결 coding 복사
'''

shop/templates/shop/delete.html
{% extends 'base.html' %}

{% block title %}- Delete{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">
            Do you want to delete {{object}}?
        </div>
        <form action="" method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

shop/templates/shop/detail.html
{% extends 'base.html' %}
{% block title %}Product Detail{% endblock %}
{% block content %}

    <div class="col">
        <div class="alert alert-info text-primary" role="alert">Detail : {{ product.author.username }}</div>

        <div class="container">
            <div class="row">
                <div class="col-4">
                    <img src="{{product.image.url}}" width="100%">
                </div>
                <div class="col">
                    <h1 class="display-6">{{product.cname}}</h1>
                    <p class="card-text">{{product.pname}}</p>
                    <h7><span class="badge badge-secondary">Description</span>{{product.description|linebreaks }}</h7>
                    <p class="card-text">Product Info Link <a href="{{ product.related_url }}" target="_blank"><ins> {{product.pname}}</ins></a></p>

                    {% if product.author.username == user.username %}
                    <a href="{% url 'shop:product_update' pk=product.id product_slug=product.slug %}" class="btn btn-outline-primary btn-xs mr-1 mt-1 float-left">Update</a>
                    <a href="{% url 'shop:product_delete' pk=product.id product_slug=product.slug %}" class="btn btn-outline-danger btn-xs mr-1 mt-1 float-left">Delete</a>
                    {% endif %}

                    {% if product.author.username != user.username %}
                    <a href="mailto:zzang@logippl.com?bcc=master@bestdada.com" class="btn btn-warning text-danger btn-xs mr-1 mt-1 float-left">Inquiry by e-mail</a>
                    {% endif %}
                    <a href="/" class="btn btn-info btn-xs mt-1 float-left">Continue shopping</a>

                </div>
            </div>

        </div>
        <p></p>

    <div class="col">
        <div class="alert alert-info" role="alert">Products added by registrants</div>


        <div class="container">
            {% for prdt in product_list %}
                {% if product.author.username == prdt.author.username %}
                    {% if product.pname != prdt.pname %}
                        <a href="{{prdt.get_absolute_url}}" class="btn btn-outline-warning mt-1 text-success ">{{ prdt }}</a><br>
                    {% endif %}
                {% endif %}

            {% endfor %}
        </div>






{% endblock %}

shop/templates/shop/list.html
{% extends 'base.html' %}
{% block title %}Category Page{% endblock %}
{% block content %}



    <div class="row">
        <div class="col-2">
            <div class="list-group">
                <a href="/" class="list-group-item {% if not current_category %}active{% endif %}">All</a>
                {% for c in categories %}
                    <a href="{{c.get_absolute_url}}" class="list-group-item {% if current_category.slug == c.slug %}active{% endif %}">{{c.name}}</a>
                {% endfor %}
            </div>
        </div>



            <div class="col">
                <div class="alert alert-info" role="alert">
                    {% if current_category %}{{current_category.name}}{% else %}All Products{% endif %}
                </div>
<!--               <div class="card-columns"> -->

                    <div class="row">
                    {% for product in products %}

                        <div class="col-4">
                            <div class="card">
                              <img class="card-img-top" src="{{product.image.url}}" alt="Product Image" >
                              <div class="card-body">
                                {% if product.author.username != user.username %}
                               <button type="button" class="btn btn-xs btn-outline-warning text-secondary " disabled>{{product.author.username}}</button>
                                {% endif %}
                                 {% if product.author.username == user.username %}
                               <button type="button" class="btn btn-xs btn-info" disabled>{{product.author.username}}</button>
                                 {% endif %}
                               <h4 class="card-title mt-1">{{product.pname}}</h4>
                                  <h5 class="card-subtitle mb-2 text-muted">{{product.cname}}</h5>
                                  <p class="card-text"><small>{{product.description|slice:":30"}} ...</small></p>
                                  <h4 class="text-warning"><em><strong>{{product.category.name}}</strong></em></h4>

                                 {% if product.author.username == user.username %}
                               <a href="{% url 'shop:product_update' pk=product.id product_slug=product.slug %}" class="btn btn-outline-success btn-xs mr-1 mt-1 float-left">Update</a>
                               <a href="{% url 'shop:product_delete' pk=product.id product_slug=product.slug %}" class="btn btn-outline-danger btn-xs mr-1 mt-1 float-left">Delete</a>
                                 {% endif %}

                               <a href="{{product.get_absolute_url}}" class="btn btn-primary mt-1">View Detail</a>
                              </div>
                            </div>
                        </div>

                        {% endfor %}
                    </div>
<!--                </div>  -->
            </div>



{% endblock %}

shop/templates/shop/mypage.html
{% extends 'base.html' %}
{% block title %}Product Detail{% endblock %}
{% block content %}


    <div class="col">
        <div class="alert alert-info" role="alert">My Prodeucts</div>


        <div class="container">
            {% for product in products %}
            <div class="row">

                {% if product.author.username == user.username %}
                <div class="col-4">
                    <img src="{{product.image.url}}" width="auto" height="250">
                </div>
                <div class="col">
                    <h1 class="display-6">{{product.pname}}</h1>
                    <h5><span class="badge badge-secondary">Description</span>{{product.description|linebreaks}}</h5>
                    <a href="{% url 'shop:product_update' pk=product.id product_slug=product.slug %}" class="btn btn-outline-primary btn-xs mt-1 mr-1float-left">Update</a>
                    <a href="{% url 'shop:product_delete' pk=product.id product_slug=product.slug %}" class="btn btn-outline-danger btn-xs mt-1 mr-1float-left">Delete</a>
                    <a href="/" class="btn btn-info mt-1 mr-1 float-left">Continue shopping</a>
                </div>

                {% endif %}
            </div>
            <p></p>

            {% endfor %}

        </div>



{% endblock %}

shop/templates/shop/update.html
{% extends 'base.html' %}

{% block title %}- Update{% endblock %}

{% block content %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <form action="" method="post" enctype="multipart/form-data">
                    {{form.as_p}}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Update">
<!--                    <p>Name : model / Slug : model, keyword ...</p> -->

                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
{% endblock %}

shop/templates/shop/upload.html
{% extends 'base.html' %}

{% block title %}- Upload{% endblock %}

{% block content %}
    <div class="col">
        <div class="alert alert-info" role="alert">Product Upload</div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <form action="" method="post" enctype="multipart/form-data"> <!-- enctype="multipart/form-data" : 파일 업로드일때 사용하는 옵션이며 데이터를 문자열로 인코딩 하지 않고 전달합니다. -->
                    {{form.as_p}}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Upload">
                    <p></p>
<!--                    <p>Name : model</p>
                    <p>Slug : model, keyword ...</p> -->
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock %}

<!-- 28. localhost에서 사진 표시 하기 위해 .config/urls.py에 coding 삽입  -->